/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Renan
 */
public class Acomp_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Acomp_GUI
     */
    public Acomp_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        A1_BTN = new javax.swing.JButton();
        A3_BTN = new javax.swing.JButton();
        A2_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        A1_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Batata-frita.png"))); // NOI18N
        A1_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(A1_BTN);
        A1_BTN.setBounds(20, 30, 170, 150);

        A3_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Asinha de Frango.png"))); // NOI18N
        A3_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(A3_BTN);
        A3_BTN.setBounds(20, 210, 170, 150);

        A2_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Nuggets.png"))); // NOI18N
        A2_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(A2_BTN);
        A2_BTN.setBounds(200, 30, 170, 150);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 450);

        setSize(new java.awt.Dimension(400, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void A1_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1_BTNActionPerformed
       Controller.Add_DAO.adicionarProduto("Batata Frita");
       Controller.Busca_DAO.refresh();
    }//GEN-LAST:event_A1_BTNActionPerformed

    private void A2_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2_BTNActionPerformed
       Controller.Add_DAO.adicionarProduto("Nuggets");
              Controller.Busca_DAO.refresh();

    }//GEN-LAST:event_A2_BTNActionPerformed

    private void A3_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3_BTNActionPerformed
       Controller.Add_DAO.adicionarProduto("Asinha de Frango");
              Controller.Busca_DAO.refresh();

    }//GEN-LAST:event_A3_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acomp_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acomp_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acomp_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acomp_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acomp_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1_BTN;
    private javax.swing.JButton A2_BTN;
    private javax.swing.JButton A3_BTN;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
