/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Renan
 */
public class Bedidas_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Bedidas_GUI
     */
    public Bedidas_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        B2_BTN = new javax.swing.JButton();
        B3_BTN = new javax.swing.JButton();
        B1_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        B2_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Suco.png"))); // NOI18N
        B2_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(B2_BTN);
        B2_BTN.setBounds(200, 30, 170, 150);

        B3_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Milkshake.png"))); // NOI18N
        B3_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(B3_BTN);
        B3_BTN.setBounds(30, 220, 170, 170);

        B1_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Refrigerante.png"))); // NOI18N
        B1_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(B1_BTN);
        B1_BTN.setBounds(20, 20, 170, 170);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 450);

        setSize(new java.awt.Dimension(400, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B1_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1_BTNActionPerformed
            Controller.Add_DAO.adicionarProduto("Refrigerante");
       Controller.Busca_DAO.refresh();

    }//GEN-LAST:event_B1_BTNActionPerformed

    private void B2_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2_BTNActionPerformed
       Controller.Add_DAO.adicionarProduto("Suco");
              Controller.Busca_DAO.refresh();

    }//GEN-LAST:event_B2_BTNActionPerformed

    private void B3_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3_BTNActionPerformed
       Controller.Add_DAO.adicionarProduto("Milkshake");
              Controller.Busca_DAO.refresh();

    }//GEN-LAST:event_B3_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bedidas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bedidas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bedidas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bedidas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bedidas_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1_BTN;
    private javax.swing.JButton B2_BTN;
    private javax.swing.JButton B3_BTN;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
