/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Renan
 */
public class Combo_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Combo_GUI
     */
    public Combo_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        C1_BTN = new javax.swing.JButton();
        C3_BTN = new javax.swing.JButton();
        C2_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        C1_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Combo Fritas.png"))); // NOI18N
        C1_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(C1_BTN);
        C1_BTN.setBounds(20, 40, 170, 150);

        C3_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Combo Completo.png"))); // NOI18N
        C3_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(C3_BTN);
        C3_BTN.setBounds(20, 230, 170, 150);

        C2_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Combo Bebida.png"))); // NOI18N
        C2_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(C2_BTN);
        C2_BTN.setBounds(210, 40, 170, 150);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 450);

        setSize(new java.awt.Dimension(400, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void C1_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1_BTNActionPerformed
       Controller.Add_DAO.adicionarProduto("Combo Fritas");
              Controller.Busca_DAO.refresh();

    }//GEN-LAST:event_C1_BTNActionPerformed

    private void C2_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2_BTNActionPerformed
       Controller.Add_DAO.adicionarProduto("Combo Bebida");
              Controller.Busca_DAO.refresh();

    }//GEN-LAST:event_C2_BTNActionPerformed

    private void C3_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3_BTNActionPerformed
       Controller.Add_DAO.adicionarProduto("Combo Completo");
              Controller.Busca_DAO.refresh();

    }//GEN-LAST:event_C3_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Combo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Combo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Combo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Combo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Combo_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C1_BTN;
    private javax.swing.JButton C2_BTN;
    private javax.swing.JButton C3_BTN;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
