/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Renan
 */
public class CPF_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CPF_GUI
     */
    public CPF_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CPF_TXT = new javax.swing.JTextField();
        CPF2_BTN = new javax.swing.JButton();
        CPF1_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Insira seu CPF:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 50, 140, 52);
        jPanel1.add(CPF_TXT);
        CPF_TXT.setBounds(100, 130, 190, 40);

        CPF2_BTN.setBackground(new java.awt.Color(204, 255, 255));
        CPF2_BTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CPF2_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nao.png"))); // NOI18N
        CPF2_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPF2_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(CPF2_BTN);
        CPF2_BTN.setBounds(140, 360, 110, 30);

        CPF1_BTN.setBackground(new java.awt.Color(204, 255, 255));
        CPF1_BTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CPF1_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/inserir.png"))); // NOI18N
        CPF1_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPF1_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(CPF1_BTN);
        CPF1_BTN.setBounds(140, 280, 110, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 450);

        setSize(new java.awt.Dimension(400, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CPF1_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPF1_BTNActionPerformed
        JOptionPane.showMessageDialog(null, "CPF Registrado!");
       Controller.Busca_DAO.refresh();

        new Nome_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CPF1_BTNActionPerformed

    private void CPF2_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPF2_BTNActionPerformed
        JOptionPane.showMessageDialog(null, "CPF não registrado!");
               Controller.Busca_DAO.refresh();

        new Nome_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CPF2_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CPF_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CPF_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CPF_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CPF_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CPF_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton CPF1_BTN;
    public static javax.swing.JButton CPF2_BTN;
    public static javax.swing.JTextField CPF_TXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
