/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Renan
 */
public class Desc_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Desc_GUI
     */
    public Desc_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        n1_btn = new javax.swing.JButton();
        n1_btn1 = new javax.swing.JButton();
        n1_btn2 = new javax.swing.JButton();
        n1_btn3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        n1_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/caixa.png"))); // NOI18N
        n1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1_btnActionPerformed(evt);
            }
        });
        jPanel1.add(n1_btn);
        n1_btn.setBounds(30, 270, 140, 120);

        n1_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/caixa.png"))); // NOI18N
        n1_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(n1_btn1);
        n1_btn1.setBounds(30, 130, 140, 130);

        n1_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/caixa.png"))); // NOI18N
        n1_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1_btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(n1_btn2);
        n1_btn2.setBounds(220, 270, 140, 120);

        n1_btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/caixa.png"))); // NOI18N
        n1_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1_btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(n1_btn3);
        n1_btn3.setBounds(220, 130, 140, 130);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Escolha a Caixa");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 40, 160, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 450);

        setSize(new java.awt.Dimension(400, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void n1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1_btnActionPerformed
        Controller.DESC_DAO.Desc2();
        new DescF2_GUI().setVisible(true);
this.dispose();
       Controller.Busca_DAO.refresh();

    }//GEN-LAST:event_n1_btnActionPerformed

    private void n1_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1_btn1ActionPerformed
        Controller.DESC_DAO.Desc1();
               Controller.Busca_DAO.refresh();

new DescF_GUI().setVisible(true); this.dispose();    }//GEN-LAST:event_n1_btn1ActionPerformed

    private void n1_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1_btn2ActionPerformed
                Controller.DESC_DAO.Desc3();
                       Controller.Busca_DAO.refresh();

        new DescF3_GUI().setVisible(true);
this.dispose();
    }//GEN-LAST:event_n1_btn2ActionPerformed

    private void n1_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1_btn3ActionPerformed
               Controller.DESC_DAO.Desc4();
                      Controller.Busca_DAO.refresh();

        new DescF4_GUI().setVisible(true);
this.dispose();
    }//GEN-LAST:event_n1_btn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desc_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desc_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desc_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desc_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desc_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton n1_btn;
    private javax.swing.JButton n1_btn1;
    private javax.swing.JButton n1_btn2;
    private javax.swing.JButton n1_btn3;
    // End of variables declaration//GEN-END:variables
}
