/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Renan
 */
public class Geral_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Geral_GUI
     */
    public Geral_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LANCHES_BTN = new javax.swing.JButton();
        BEBIDAS_BTN = new javax.swing.JButton();
        ACOMPANHAMENTOS_BTN = new javax.swing.JButton();
        COMBOS_BTN = new javax.swing.JButton();
        Cancelar_BTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Sobremesa_BTN = new javax.swing.JButton();
        Finaliza_BTN1 = new javax.swing.JButton();
        subtotal_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        LANCHES_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Lanches.png"))); // NOI18N
        LANCHES_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LANCHES_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(LANCHES_BTN);
        LANCHES_BTN.setBounds(10, 50, 90, 110);

        BEBIDAS_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Bebidas.png"))); // NOI18N
        BEBIDAS_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEBIDAS_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(BEBIDAS_BTN);
        BEBIDAS_BTN.setBounds(10, 170, 90, 110);

        ACOMPANHAMENTOS_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Acompanhamentos.png"))); // NOI18N
        ACOMPANHAMENTOS_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACOMPANHAMENTOS_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(ACOMPANHAMENTOS_BTN);
        ACOMPANHAMENTOS_BTN.setBounds(10, 290, 90, 110);

        COMBOS_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Combos.png"))); // NOI18N
        COMBOS_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMBOS_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(COMBOS_BTN);
        COMBOS_BTN.setBounds(10, 530, 90, 110);

        Cancelar_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Cancelar.png"))); // NOI18N
        Cancelar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar_BTN);
        Cancelar_BTN.setBounds(130, 660, 110, 70);

        jLabel1.setText("------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 640, 620, 16);

        Sobremesa_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Sobremesas.png"))); // NOI18N
        Sobremesa_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sobremesa_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(Sobremesa_BTN);
        Sobremesa_BTN.setBounds(10, 410, 90, 110);

        Finaliza_BTN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/proximo.png"))); // NOI18N
        Finaliza_BTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Finaliza_BTN1ActionPerformed(evt);
            }
        });
        jPanel1.add(Finaliza_BTN1);
        Finaliza_BTN1.setBounds(10, 660, 110, 70);

        subtotal_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotal_txtActionPerformed(evt);
            }
        });
        jPanel1.add(subtotal_txt);
        subtotal_txt.setBounds(430, 680, 140, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Subtotal:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 680, 80, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menu.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 0, 280, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 750);

        setSize(new java.awt.Dimension(600, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void COMBOS_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBOS_BTNActionPerformed
        new Combo_GUI().setVisible(true);
    }//GEN-LAST:event_COMBOS_BTNActionPerformed

    private void LANCHES_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LANCHES_BTNActionPerformed
        new Lanche_GUI().setVisible(true);
    }//GEN-LAST:event_LANCHES_BTNActionPerformed

    private void Sobremesa_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sobremesa_BTNActionPerformed
        new Sobremesa_GUI().setVisible(true);
    }//GEN-LAST:event_Sobremesa_BTNActionPerformed

    private void ACOMPANHAMENTOS_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACOMPANHAMENTOS_BTNActionPerformed
        new Acomp_GUI().setVisible(true);
    }//GEN-LAST:event_ACOMPANHAMENTOS_BTNActionPerformed

    private void BEBIDAS_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEBIDAS_BTNActionPerformed
        new Bedidas_GUI().setVisible(true);
    }//GEN-LAST:event_BEBIDAS_BTNActionPerformed

    private void Cancelar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_BTNActionPerformed
        Controller.Deleta_DAO.cancelarPedido();
               Controller.Busca_DAO.refresh();

       
    }//GEN-LAST:event_Cancelar_BTNActionPerformed

    private void Finaliza_BTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Finaliza_BTN1ActionPerformed
        new CPF_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Finaliza_BTN1ActionPerformed

    private void subtotal_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotal_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotal_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Geral_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Geral_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Geral_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Geral_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Geral_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACOMPANHAMENTOS_BTN;
    private javax.swing.JButton BEBIDAS_BTN;
    private javax.swing.JButton COMBOS_BTN;
    private javax.swing.JButton Cancelar_BTN;
    private javax.swing.JButton Finaliza_BTN1;
    private javax.swing.JButton LANCHES_BTN;
    private javax.swing.JButton Sobremesa_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField subtotal_txt;
    // End of variables declaration//GEN-END:variables
}
