/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Renan
 */
public class Lanche_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Lanche_GUI
     */
    public Lanche_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        L1_BTN = new javax.swing.JButton();
        L5_BTN = new javax.swing.JButton();
        L4_BTN = new javax.swing.JButton();
        L2_BTN = new javax.swing.JButton();
        L3_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        L1_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/XBacon.png"))); // NOI18N
        L1_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L1_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(L1_BTN);
        L1_BTN.setBounds(30, 30, 130, 110);

        L5_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/XFrango.png"))); // NOI18N
        L5_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L5_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(L5_BTN);
        L5_BTN.setBounds(30, 280, 130, 110);

        L4_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/XTudo.png"))); // NOI18N
        L4_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L4_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(L4_BTN);
        L4_BTN.setBounds(190, 150, 130, 110);

        L2_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/XSalada.png"))); // NOI18N
        L2_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(L2_BTN);
        L2_BTN.setBounds(190, 30, 130, 110);

        L3_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/XBurguer.png"))); // NOI18N
        L3_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(L3_BTN);
        L3_BTN.setBounds(30, 150, 130, 110);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 450);

        setSize(new java.awt.Dimension(400, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void L1_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L1_BTNActionPerformed
       Controller.Add_DAO.adicionarProduto("X-Bacon");
              Controller.Busca_DAO.refresh();

    }//GEN-LAST:event_L1_BTNActionPerformed

    private void L2_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2_BTNActionPerformed
       Controller.Add_DAO.adicionarProduto("X-Salada");
              Controller.Busca_DAO.refresh();

    }//GEN-LAST:event_L2_BTNActionPerformed

    private void L3_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3_BTNActionPerformed
       Controller.Add_DAO.adicionarProduto("X-Burguer");
              Controller.Busca_DAO.refresh();

    }//GEN-LAST:event_L3_BTNActionPerformed

    private void L4_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L4_BTNActionPerformed
       Controller.Add_DAO.adicionarProduto("X-Tudo");
              Controller.Busca_DAO.refresh();

    }//GEN-LAST:event_L4_BTNActionPerformed

    private void L5_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L5_BTNActionPerformed
       Controller.Add_DAO.adicionarProduto("X-Frango");
              Controller.Busca_DAO.refresh();

    }//GEN-LAST:event_L5_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lanche_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lanche_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lanche_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lanche_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lanche_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton L1_BTN;
    public static javax.swing.JButton L2_BTN;
    public static javax.swing.JButton L3_BTN;
    private javax.swing.JButton L4_BTN;
    private javax.swing.JButton L5_BTN;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
