/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Renan
 */
public class Pag_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Pag_GUI
     */
    public Pag_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Din_BTN = new javax.swing.JButton();
        Pix_BTN = new javax.swing.JButton();
        Deb_BTN = new javax.swing.JButton();
        Cre_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        Din_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dinheiro.png"))); // NOI18N
        Din_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Din_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(Din_BTN);
        Din_BTN.setBounds(50, 240, 130, 140);

        Pix_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pix.png"))); // NOI18N
        Pix_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pix_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(Pix_BTN);
        Pix_BTN.setBounds(220, 240, 130, 140);

        Deb_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/debito.png"))); // NOI18N
        Deb_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deb_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(Deb_BTN);
        Deb_BTN.setBounds(50, 40, 130, 140);

        Cre_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/credito.png"))); // NOI18N
        Cre_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cre_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(Cre_BTN);
        Cre_BTN.setBounds(220, 40, 130, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 450);

        setSize(new java.awt.Dimension(400, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Pix_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pix_BTNActionPerformed
       new PagPix_GUI().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Pix_BTNActionPerformed

    private void Cre_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cre_BTNActionPerformed
       new PagCredito_GUI().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Cre_BTNActionPerformed

    private void Deb_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deb_BTNActionPerformed
        new PagDebito_GUI().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Deb_BTNActionPerformed

    private void Din_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Din_BTNActionPerformed
        new PagDinheiro_GUI().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Din_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pag_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pag_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pag_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pag_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pag_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cre_BTN;
    private javax.swing.JButton Deb_BTN;
    private javax.swing.JButton Din_BTN;
    private javax.swing.JButton Pix_BTN;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
